- title: Modes
  type: entities
  entities:
    - input_boolean.night_mode
    - input_boolean.force_away
    - input_boolean.force_presence
    - input_boolean.cover_mode
    - input_boolean.holiday_mode
    - input_boolean.notifications

- title: Prix
  type: entities
  entities:
    - input_number.elec_price
  
- title: Seuils
  type: entities
  entities:
    - input_number.cloud_treshold
    - input_number.open_cover_temperature_treshold
    - input_number.low_alert_temperature
    - input_number.high_alert_temperature

- title: Notifications
  type: entities
  entities:
    - input_boolean.notifications
    - input_text.notifications_generic_title
    - type: divider
    - input_text.notifications_ha_start
    - input_text.notifications_ha_stop
    - type: divider
    - input_text.notifications_title_presence
    - input_text.notifications_message_presence
    - type: divider
    - input_text.notifications_title_away_mode_on
    - input_text.notifications_message_away_mode_on
    - type: divider
    - input_text.notifications_title_away_mode_off
    - input_text.notifications_message_away_mode_off
    

