- id: coucher_de_soleil
  alias: Coucher de soleil
  trigger:
    platform: sun    
    event: sunset    
    offset: '00:25:00'
  action:
    service: cover.close_cover
    entity_id: group.all_covers
- id: veilleuse
  alias: Veilleuse
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.yeelight_rgb_34ce008bc436
      brightness: 25