- id: coucher_de_soleil
  alias: Coucher de soleil
  trigger:
    platform: sun    
    event: sunset    
    offset: '00:25:00'
  action:
    service: cover.close_cover
    entity_id: group.all_covers