- id: coucher_de_soleil
  alias: Coucher de soleil
  trigger:
  - event: sunset
    offset: 00:20:00
    platform: sun
  action:
    - entity_id: group.all_covers
      service: cover.close_cover

- id: veilleuse
  alias: Veilleuse
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  - condition: state
    entity_id: light.salon
    state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.salon
        brightness: 10
    - delay: 00:02:30
    - service: light.turn_off
      data:
        entity_id: light.salon

- id: night_mode_on
  alias: Mode nuit
  trigger:
    platform: state
    entity_id: input_boolean.night_mode
    to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.salon
    - service: switch.turn_off
      data:
        entity_id: switch.neo_coolcam_power_plug_12a_switch_3

- id: night_mode_off
  alias: Lever
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.salon
      brightness: 25
  - service: switch.turn_on
    data:
      entity_id: switch.neo_coolcam_power_plug_12a_switch_3
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.night_mode

- id: leave_home
  alias: Départ
  trigger:
    platform: template
    value_template: "{{not (is_state('device_tracker.honor_marc', 'home') or is_state('device_tracker.honor_eva', 'home')) and is_state('switch.neo_coolcam_power_plug_12a_switch_2', 'off') }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_mode
    - service: switch.turn_on
      data:
        entity_id: switch.neo_coolcam_power_plug_12a_switch_2

- id: coming_home
  alias: Retour
  trigger:
    - platform: zone
      entity_id: device_tracker.honor_marc
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.honor_eva
      zone: zone.home
      event: enter
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_mode
    - service: switch.turn_off
      data:
        entity_id: switch.neo_coolcam_power_plug_12a_switch_2

- id: timer_chromecast
  alias: Minuteur Chromecast
  trigger:
    platform: state
    entity_id: input_number.tv_timer
  condition:
    - condition: template
      value_template: '{{ states.input_number.tv_timer.state | int != 0 }}'
  action:
    - delay: '00:{{ states.input_number.tv_timer.state | int }}:00'
    - service: media_player.turn_off
      data:
        entity_id: media_player.chromecast_salon 
    - service: input_number.set_value
      data:
        entity_id: input_number.tv_timer
        value: 0

- id: start_power
  alias: Allumage prise
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.prise_garage
    - delay: 00:05:00
    - service: script.eteindre_prise_garage

- id: car_charging
  alias: Recharge voiture
  trigger:
    platform: numeric_state
    entity_id: sensor.prise_garage
    above: 1500
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.garage_charging
    
- id: car_charged
  alias: Voiture chargée
  trigger:
    platform: numeric_state
    entity_id: sensor.prise_garage
    below: 500
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.garage_charging
    - delay: 00:01:00
    - service: script.eteindre_prise_garage

- id: main_cover_opened
  alias: Eteindre lumière
  trigger:
    platform: state
    entity_id: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level
    to: 'open'
  action:
    - service: light.turn_off
      data:
        entity_id: light.salon
    - service: switch.turn_off
      data:
        entity_id: switch.neo_coolcam_power_plug_12a_switch_3

- id: leaving_sii
  alias: test leave sii
  trigger:
    - platform: zone
      entity_id: device_tracker.honor_marc
      zone: zone.sii
      event: leave
  action:
    - service: notify.html5
      data:
        message: "Marc is leaving SII"
        title: "Bye !"    

- id: ha_start
  alias: Démarrage Home Assistant
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.html5
      data:
        message: "Starting..."
        title: "HomeAssistant"

- id: ha_stop
  alias: Arrêt Home Assistant
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.html5
      data:
        message: "Stopping !"
        title: "HomeAssistant"

- id: notify_away
  alias: Notification absence
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: notify.html5
      data:
        title: "Home Assistant"
        message: "Absence activée"
        target: 
          - "Honor Marc"