homeassistant:
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  include:
    domains:
      - automation
      - input_boolean
      - light
      - media_player
      - sun
    entities:
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_2
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_3
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_4
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_5
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_6
      - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_7
      - sensor.fibaro_system_fgms001_motion_sensor_temperature
      - sensor.fibaro_system_fgsd002_smoke_sensor_temperature
      - binary_sensor.fibaro_system_fgms001_motion_sensor_sensor

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mqtt: 

# Weather prediction
sensor:  
  - platform: google_travel_time
    api_key: !secret google_map_api_key
    origin: zone.Home
    destination: zone.SII
    name: vers SII
  - platform: google_travel_time
    api_key: !secret google_map_api_key
    origin: zone.Home
    destination: CA St Martin
    name: vers St Martin
  - platform: google_travel_time
    api_key: !secret google_map_api_key
    origin: zone.Home
    destination: CA Bourg L'Evêque
    name: vers Bourg L'Evêque

  - platform: speedtest
    minute: 30
    hour:
      - 8
      - 18
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: fastdotcom
    hour:
      - 9
      - 19

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: load_15m

light:
  - platform: yeelight
    devices:
      192.168.0.9:
        name: Chambre Axelle
      192.168.0.2:
        name: Salon
      192.168.0.26:
        name: Bandeau LED

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

camera:
  - platform: generic
    name: Salon
    still_image_url: >
      {% if is_state('switch.neo_coolcam_power_plug_12a_switch_2','on') %}
        http://192.168.0.8/image.jpg
      {% else %}
        http://127.0.0.1:8123/local/camera-off.png
      {% endif %}
    limit_refetch_to_url_change: false

zwave:
  usb_path: /dev/ttyACM0

input_boolean:
  night_mode:
    name: Mode nuit
    icon: mdi:weather-night
  away_mode:
    name: Absence
    icon: mdi:account-remove
  holiday_mode:
    name: Congés
    icon: mdi:sunglasses

binary_sensor:
  - platform: workday
    country: FRA


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
