- platform: slack
  name: slack
  api_key: !secret slack_oauth_token
  default_channel: '#domotique'
  username: 'Home Assistant'
  icon: ':homeassistant:'

- name: html5
  platform: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id