- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m

- platform: template
  sensors:
    power_prise_garage:
      entity_id: switch.prise_garage
      icon_template: mdi:power-plug
      value_template: "{{ states.switch.prise_garage.attributes.current_power_w|default(0)|float }}"
      unit_of_measurement: W
    ## CAR CHARGE
    value_day_car_charge:
      entity_id: sensor.day_car_charge
      friendly_name: Durée de recharge
      icon_template: mdi:timer-sand
      value_template: "{{ states.sensor.day_car_charge.attributes.value }}"
    value_month_car_charge:
      entity_id: sensor.month_car_charge
      friendly_name: Durée mensuelle
      icon_template: mdi:timer-sand
      value_template: "{{ states.sensor.month_car_charge.attributes.value }}"
    power_day_car_charge:
      entity_id: 
        - sensor.day_car_charge
      friendly_name: Consommation
      unit_of_measurement: kW
      icon_template: mdi:gas-station
      value_template: "{{(states.sensor.day_car_charge.state|float * 2.2) | round(2)}}"
    power_month_car_charge:
      entity_id: 
        - sensor.month_car_charge
      friendly_name: Consommation
      unit_of_measurement: kW
      icon_template: mdi:gas-station
      value_template: "{{(states.sensor.month_car_charge.state|float * 2.2) | round(2)}}"
    price_day_car_charge:
      entity_id: 
        - sensor.day_car_charge
        - input_number.elec_price
      friendly_name: Coût de recharge
      unit_of_measurement: €
      icon_template: mdi:currency-eur
      value_template: "{{(states.sensor.day_car_charge.state|float * states.input_number.elec_price.state|float * 2.2) | round(2)}}"
    price_month_car_charge:
      entity_id: 
        - sensor.month_car_charge
        - input_number.elec_price
      friendly_name: Coût de recharge mensuel
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{(states.sensor.month_car_charge.state|float * states.input_number.elec_price.state|float * 2.2) | round(2)}}"
    charge_estimated_time_minute:
      entity_id: 
        - input_number.battery_left
        - input_number.battery_max
      friendly_name: Temps de chargement
      icon_template: mdi:timer-sand
      unit_of_measurement: mn
      value_template: "{{((states.input_number.battery_max.state|int - states.input_number.battery_left.state|int) / 100 * 19 / 2.2 * 60)|int }}"
    charge_estimated_time_hour:
      entity_id: 
        - sensor.charge_estimated_time_minute
      friendly_name: Temps de chargement estimé
      icon_template: mdi:timer-sand
      unit_of_measurement: h
      value_template: "{{(states.sensor.charge_estimated_time_minute.state|int / 60)|round(2)}}"

    ## SUN ##
    sunset:
      entity_id: sun.sun
      friendly_name: Coucher du soleil
      icon_template: mdi:weather-sunset-down
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%d/%m/%Y %H:%M',true)}}"
    sunrise:
      entity_id: sun.sun
      friendly_name: Lever du soleil
      icon_template: mdi:weather-sunset-up
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%d/%m/%Y %H:%M',true)}}"

    ## WAZE
    waze_dm_roads:
      entity_id: sensor.waze_dm
      friendly_name: Routes DEVmachine
      icon_template: mdi:road-variant
      value_template: "{{ states.sensor.waze_dm.attributes.route }}"

    ## CAST
    cast_app_name:
      entity_id: media_player.salon
      friendly_name: Application
      icon_template: mdi:cast
      value_template: "{{ states.media_player.salon.attributes.app_name|default('empty') }}" 

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 1
    - 2
    - 3
    - 4
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - humidity
    - precip_probability
    - wind_speed
    - cloud_cover
    - temperature_high
    - temperature_low
    - uv_index
  scan_interval: '00:30'

- platform: history_stats
  name: month_count_car_charge
  entity_id: input_boolean.car_charging
  state: 'on'
  type: count
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: month_car_charge
  entity_id: input_boolean.car_charging
  state: 'on'
  type: time
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: day_car_charge
  entity_id: input_boolean.car_charging
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: statistics
  entity_id: sensor.power_prise_garage  
  name: prise_garage

- platform: waze_travel_time
  origin: zone.home
  destination: zone.DEVmachine
  region: 'EU'
  name: 'waze dm'

- platform: seventeentrack
  username: !secret 17track_user
  password: !secret 17track_pass
