- platform: google_travel_time
  api_key: !secret google_map_api_key
  origin: zone.Home
  destination: zone.SII
  name: vers SII

- platform: google_travel_time
  api_key: !secret google_map_api_key
  origin: zone.Home
  destination: CA St Martin
  name: vers St Martin
- platform: google_travel_time
  api_key: !secret google_map_api_key
  origin: zone.Home
  destination: CA Bourg L'Evêque
  name: vers Bourg L'Evêque

- platform: speedtest
  minute: 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: fastdotcom
  minute: 45

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m

- platform: broadlink_power
  host: 192.168.0.25
  mac: '34:EA:34:9D:27:5C'
  name: Prise garage

- platform: template
  sensors:
    garage_plug:
      unit_of_measurement: charge
      friendly_name: Garage
      value_template: >-
        {% if is_state('switch.prise_garage', 'off') %}
          Off        
        {% elif is_state('input_boolean.garage_charging','true') %}          
          {% if states('sensor.prise_garage')|float > 1500 %}
            Voiture
          {% else %}
            Attente
          {% endif %}         
        {% else %}
          On
        {% endif %}
    value_day_car_charge:
      friendly_name: Durée de recharge
      icon_template: mdi:timer-sand
      value_template: "{{ states.sensor.day_car_charge.attributes.value }}"
    value_month_car_charge:
      friendly_name: Durée mensuelle
      icon_template: mdi:timer-sand
      value_template: "{{ states.sensor.month_car_charge.attributes.value }}"
    price_day_car_charge:
      friendly_name: Coût de recharge
      unit_of_measurement: €
      icon_template: mdi:currency-eur
      value_template: "{{(states.sensor.day_car_charge.state|float * states.input_number.elec_price.state|float * 2.3) | round(2)}}"
    price_month_car_charge:
      friendly_name: Coût de recharge mensuel
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{(states.sensor.month_car_charge.state|float * states.input_number.elec_price.state|float * 2.3) | round(2)}}"
    sunset:
      friendly_name: Coucher du soleil
      icon_template: mdi:weather-sunset-down
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%d/%m/%Y %H:%M',true)}}"
    sunrise:
      friendly_name: Lever du soleil
      icon_template: mdi:weather-sunset-up
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%d/%m/%Y %H:%M',true)}}"
    smoke_sensor_upstair_battery:
      value_template: "{{states.zwave.fibaro_system_fgsd002_smoke_sensor.attributes.battery_level}}"
      unit_of_measurement: '%'
      icon_template: >-
        {% if states.zwave.fibaro_system_fgsd002_smoke_sensor.attributes.battery_level|int < 10 %}
          mdi:battery-alert
        {% elif is_state_attr('zwave.fibaro_system_fgsd002_smoke_sensor', 'battery_level', 100) %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.zwave.fibaro_system_fgsd002_smoke_sensor.attributes.battery_level|int // 10) * 10}}
        {% endif %}

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 1
    - 2
    - 3
    - 4
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - humidity
    - precip_probability
    - wind_speed
    - cloud_cover
    - temperature_max
    - temperature_min
  update_interval: '00:05'

- platform: history_stats
  name: month_car_charge
  entity_id: input_boolean.garage_charging
  state: 'on'
  type: time
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: day_car_charge
  entity_id: input_boolean.garage_charging
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: statistics
  entity_id: sensor.prise_garage  
  name: prise_garage