- platform: google_travel_time
  api_key: !secret google_map_api_key
  origin: zone.Home
  destination: zone.SII
  name: vers SII

- platform: google_travel_time
  api_key: !secret google_map_api_key
  origin: zone.Home
  destination: CA St Martin
  name: vers St Martin
- platform: google_travel_time
  api_key: !secret google_map_api_key
  origin: zone.Home
  destination: CA Bourg L'Evêque
  name: vers Bourg L'Evêque

- platform: speedtest
  minute: 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: fastdotcom
  minute: 45

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m

- platform: broadlink_power
  host: 192.168.0.25
  mac: '34:EA:34:9D:27:5C'
  name: Prise garage

- platform: template
  sensors:
    garage_plug:
      friendly_name_template: >-
        {% if is_state('switch.prise_garage', 'off') %}
          Garage
        {% elif states('sensor.prise_garage')|float > 2000 %}
          Voiture
        {% else %}
          Garage
        {% endif %}
      icon_template: >-
        {% if is_state('swicth.prise_garage', 'off') %}
          mdi:power-plug-off
        {% elif states('sensor.prise_garage')|float > 2000 %}
          mdi:battery-charging-30
        {% else %}
          mdi:battery-charging
        {% endif %}
      value_template: >-
        {% if is_state('switch.prise_garage', 'off') %}
          Rien
        {% elif states('sensor.prise_garage')|float > 2000 %}
          Voiture
        {% else %}
          Chargé
        {% endif %}        