- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: load_15m

- platform: broadlink_power
  host: 192.168.0.25
  mac: '34:EA:34:9D:27:5C'
  friendly_name: Prise garage

- platform: template
  sensors:
    ## CAR CHARGE
    value_day_car_charge:
      entity_id: sensor.day_car_charge
      friendly_name: Durée de recharge
      icon_template: mdi:timer-sand
      value_template: "{{ states.sensor.day_car_charge.attributes.value }}"
    value_month_car_charge:
      entity_id: sensor.month_car_charge
      friendly_name: Durée mensuelle
      icon_template: mdi:timer-sand
      value_template: "{{ states.sensor.month_car_charge.attributes.value }}"
    price_day_car_charge:
      entity_id: 
        - sensor.day_car_charge
        - input_number.elec_price
      friendly_name: Coût de recharge
      unit_of_measurement: €
      icon_template: mdi:currency-eur
      value_template: "{{(states.sensor.day_car_charge.state|float * states.input_number.elec_price.state|float * 2.2) | round(2)}}"
    price_month_car_charge:
      entity_id: 
        - sensor.month_car_charge
        - input_number.elec_price
      friendly_name: Coût de recharge mensuel
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{(states.sensor.month_car_charge.state|float * states.input_number.elec_price.state|float * 2.2) | round(2)}}"
    charge_estimated_time_minute:
      entity_id: 
        - input_number.battery_left
        - input_number.battery_max
      friendly_name: Temps de chargement
      icon_template: mdi:timer-sand
      unit_of_measurement: mn
      value_template: "{{((states.input_number.battery_max.state|int - states.input_number.battery_left.state|int) / 100 * 19 / 2.2 * 60)|int }}"
    charge_estimated_time_hour:
      entity_id: 
        - sensor.charge_estimated_time_minute
      friendly_name: Temps de chargement estimé
      icon_template: mdi:timer-sand
      unit_of_measurement: h
      value_template: "{{(states.sensor.charge_estimated_time_minute.state|int / 60)|round(2)}}"

    ## SUN ##
    sunset:
      entity_id: sun.sun
      friendly_name: Coucher du soleil
      icon_template: mdi:weather-sunset-down
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%d/%m/%Y %H:%M',true)}}"
    sunrise:
      entity_id: sun.sun
      friendly_name: Lever du soleil
      icon_template: mdi:weather-sunset-up
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%d/%m/%Y %H:%M',true)}}"

    ## BATTERIES ##
    smoke_sensor_upstair_battery:
      friendly_name: Batterie détecteur fumée étage
      value_template: "{{ state_attr('zwave.fibaro_system_fgsd002_smoke_sensor','battery_level') }}"
      unit_of_measurement: '%'
      icon_template: >-
        {% if state_attr('zwave.fibaro_system_fgsd002_smoke_sensor','battery_level')|int < 10 %}
          mdi:battery-alert
        {% elif is_state_attr('zwave.fibaro_system_fgsd002_smoke_sensor', 'battery_level', 100) %}
          mdi:battery
        {% else %}
          mdi:battery-{{(state_attr('zwave.fibaro_system_fgsd002_smoke_sensor','battery_level')|int // 10) * 10}}
        {% endif %}
    motion_sensor_battery:
      friendly_name: Batterie Motion Sensor
      value_template: "{{ state_attr('zwave.fibaro_system_fgms001_motion_sensor','battery_level')}}"
      unit_of_measurement: '%'
      icon_template: >-
        {% if state_attr('zwave.fibaro_system_fgms001_motion_sensor','battery_level')|int < 10 %}
          mdi:battery-alert
        {% elif is_state_attr('zwave.fibaro_system_fgms001_motion_sensor', 'battery_level', 100) %}
          mdi:battery
        {% else %}
          mdi:battery-{{(state_attr('zwave.fibaro_system_fgms001_motion_sensor','battery_level')|int // 10) * 10}}
        {% endif %}
    remote_hank_battery:
      friendly_name: Batterie Télécommande
      value_template: "{{ state_attr('zwave.hank_hkzw_scn04_scene_controller','battery_level')}}"
      unit_of_measurement: '%'
      icon_template: >-
        {% if state_attr('zwave.hank_hkzw_scn04_scene_controller','battery_level')|int < 10 %}
          mdi:battery-alert
        {% elif is_state_attr('zwave.hank_hkzw_scn04_scene_controller', 'battery_level', 100) %}
          mdi:battery
        {% else %}
          mdi:battery-{{(state_attr('zwave.hank_hkzw_scn04_scene_controller','battery_level')|int // 10) * 10}}
        {% endif %}

    ## WAZE
    ouest_france_roads:
      entity_id: sensor.duree_waze_of
      friendly_name: Routes Ouest France
      icon_template: mdi:road-variant
      value_template: "{{ states.sensor.duree_waze_of.attributes.route }}"
    
    sii_roads:
      entity_id: sensor.duree_waze_sii
      friendly_name: Routes SII
      icon_template: mdi:road-variant
      value_template: "{{ states.sensor.duree_waze_sii.attributes.route }}"

    ## CAST
    cast_app_name:
      entity_id: media_player.salon
      friendly_name: Application
      icon_template: mdi:cast
      value_template: "{{ states.media_player.salon.attributes.app_name|default('empty') }}" 

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 1
    - 2
    - 3
    - 4
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - humidity
    - precip_probability
    - wind_speed
    - cloud_cover
    - temperature_high
    - temperature_low
    - uv_index
  update_interval: '00:30'

- platform: history_stats
  name: month_count_car_charge
  entity_id: input_boolean.garage_charging
  state: 'on'
  type: count
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: month_car_charge
  entity_id: input_boolean.garage_charging
  state: 'on'
  type: time
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: day_car_charge
  entity_id: input_boolean.garage_charging
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: statistics
  entity_id: sensor.broadlink_spx_power_sensor  
  name: prise_garage

- platform: waze_travel_time
  origin: !secret waze_home_origin
  destination: rue du breil, Rennes, France
  region: 'EU'
  name: 'Durée Waze OF'

- platform: waze_travel_time
  origin: !secret waze_home_origin
  destination: Avenue Belle Fontaine, Cesson Sevigné, France
  region: 'EU'
  name: 'Durée Waze SII'

- platform: seventeentrack
  username: !secret 17track_user
  password: !secret 17track_pass