name: Nouvoitou
views:
  - title: Aperçu
    icon: mdi:home-assistant
    cards: !include lovelace/ui-home.yaml
    path: home

  - title: Volets
    icon: mdi:garage
    cards: !include lovelace/ui-covers.yaml
    path: covers
  
  - title: Caméras
    icon: mdi:cctv
    cards: !include lovelace/ui-cameras.yaml
    path: cameras

  - title: Transport
    icon: mdi:car-side
    cards: !include lovelace/ui-car.yaml
    path: mobility
  
  - title: Meteo
    icon: mdi:weather-partly-cloudy
    cards: !include lovelace/ui-weather.yaml
    path: forecast

  - title: Media
    icon: mdi:cast
    cards: !include lovelace/ui-media.yaml
    path: media
  
  - title: Monitoring
    icon: mdi:server
    cards: !include lovelace/ui-monitoring.yaml
    path: monitoring
 
  - title: Paramètres
    icon: mdi:settings
    cards: !include lovelace/ui-settings.yaml
    path: settings